import localFont from "next/font/local";
import "./globals.css";
import BottonBar from "@/components/ui/bottonBar";
import Navbar from "@/components/ui/navbar";
import CinemaPage from "@/components/popups/cinema";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <CinemaPage />
        <main>
          {children}
        </main>
        <footer className="p-4 mt-48 bg-black text-zinc-500 w-full flex justify-center text-center">
          pixelbook @
        </footer>
        <div className="fixed bottom-0 w-full z-10 ">
          <BottonBar />
        </div>
      </body>
    </html>
  );
}
